-- Create the Individual and Society table
CREATE TABLE `Individual_and_Society` (
  `id` INT PRIMARY KEY,
  `credit`INT,
  `course_name` VARCHAR(255),
  `description` TEXT
);

-- Insert data into the Individual and Society table
INSERT INTO `Individual_and_Society` (`id`, `course_name`,`credit`, `description`) VALUES
    (1, 'ACL 200 - Literacy Practices: Birth through Adolescence', 3,'This course is designed to help students understand a) how diverse children and adolescents learn, acquire, and utilize literacy skills and engage in literacy practices in varied contexts and b) how to support children''s literacy and development through culturally relevant practices. Students will analyze how cultural values affect beliefs about what it means to be literate in childhood and adolescence, and students will examine the relationship between cultural values, literacy practices, families, and communities. Students will practice meaningful strategies that will help them understand how to integrate literacy into family and community-based settings.'),
    (2, 'COM 100 - Introduction to Communication Studies',3, 'Introduction to Communication Studies is a survey course that examines major research areas, perspectives, and theories within the field of communication studies. The course will introduce and review key approaches to the study of human interaction, rhetoric, language, persuasion, and cultural processes across diverse contexts. Specifically, the course provides an interdisciplinary framework from which students will think seriously about how culture and society are constructed in our communicative practices, explore how language and meaning structure our reality, as well as examine the social, cultural, and political impacts of human communication as it unfolds in varied fields including interpersonal communication and conflict resolution, intercultural communication, rhetoric, media studies, as well as organizational and small-group communication.'),
    (3, 'COM 240 - Interpersonal Communication',3, 'The course introduces the basic concepts and theories of interpersonal communication in personal, educational and business settings. This includes a study of self as communicator, the effect of language on others, verbal and nonverbal expression of thoughts and feelings, and factors which contribute to effective communication. Prerequisite: SPE 100 or permission of department'),
    (4, 'CRT 100 - Critical Thinking',3, 'Critical Thinking (Same as CRT 100) is designed to develop the mind and help students learn to think clearly and effectively. Through substantive readings, structured writing assignments and ongoing discussions, students will examine concrete examples from their own experience and readings and contemporary issues in the media to learn how to analyze issues, solve problems, and make informed decisions in their academic, professional, and personal lives.'),
    (5, 'CRT 120 - Critical Thinking and Social Justice',3, 'In this course, students will build and apply critical thinking skills, including making and evaluating arguments, to questions of social inequalities, especially those related to race, class, gender, and sexual orientation. Using a variety of historical, literary and theoretical texts, students will look at ways that existing power structures benefit some groups and limit or oppress others. Students will be asked to reflect on their own experiences and attitudes and consider what they can do to build a more just and equal society.'),
    (6, 'CRT 196 - Critical Thinking: Inquiry through Queer Theories',3, 'This course engages students in critical inquiry through the lenses of queer theories (e.g., theories related to the LGBTQI + spectra). Emphasizing how queer theories help thinkers across disciplines engage in observing, viewing/positioning, examining, analyzing, and constructing queer subjects, this course asks students to examine how, within and between disciplines, a) thinkers'' perceptions and investigations are influenced by ideologies related to queerness and b) thinkers employ queer theories to create diverse ways of seeing/thinking, constructing/creating about the body, gender, sex/sexuality/sexual identities. Particular attention will be paid to how queer subjects have been pathologized and marginalized and how ideologies about queer populations affect reception of creative, scholarly, and professional works.'),
    (7, 'CRT 245 - Critical Thinking and Media Literacy',3, 'Critical Thinking and Media Literacy is designed to help students become truth-seekers in the world of new media. Students develop a critical understanding of the nature of diverse media discourses – including aims to inform, entertain, and persuade – and evaluate their contents for veracity. This course exposes the students to two sets of basic concepts: First, epistemic concepts such as truth, falsity, knowledge, and belief; and second, media concepts, including both traditional (e.g., news, commentary, reporting) and contemporary ones (e.g., social networks, new media, fake news, click-bait). In addition, it provides them with analytical methods to interpret different kinds of media contents, as well as to write critical medial analysis.'),
    (8, 'ECO 100 - Introduction to Economics',3, 'This course provides an introduction to the fundamental economic concepts of production, consumption and price determination, as developed by economists over the last two centuries for understanding market economies. The class introduces students to the role of markets and economic policy in our contemporary global economy at the individual and societal level. The topics to be explored in the course span the areas of economics and economic history, and may include the banking system, social insurance programs, international trade, market regulations, the role of unions, and the federal budget. The student will come away with a broad understanding of economic issues, methods, ideas, and history.'),
    (9, 'ECO 202 - Microeconomics',3, 'This course is an introduction to the topics of microeconomics, which include market supply and demand, theories of the firm and individual behavior, competition and monopoly, externalities, public goods, and income distribution. Students will learn ways to analyze the basic economic activities of consumption and production, and how to evaluate the allocation of resources and products achieved through markets. The role of government policy in addressing markets failures will be emphasized throughout the course, with special focus on contemporary economic problems.'),
    (10, 'GWS 100 - Introduction to Gender and Women''s Studies',3, 'This introductory level, interdisciplinary course explores the basic concepts and perspectives of Gender & Women''s Studies from an intersectional angle; that is, examining the ways in which gender intersects with race, ethnicity, nationality, class, sexuality, sexual identity, disability, and other categories. The concepts of gender - the roles, behaviors, activities, and attributes that a society considers appropriate for men and women - privilege and oppression, intersectionality, and feminist praxis will be at the core of this course. After a background in the history and significance of Gender & Women''s Studies as a field of study, you will learn to critically examine how institutionalized privilege and oppression shape individual lives and intersecting identity categories.'),
    (11, 'HED 190 - Human Sexuality and Society',3, 'This course explores the intersections of sexuality and culture, looking at the social construction of sexuality, the development of sexual and relationship norms through history, and the role of media and popular culture in shaping our understanding of sexuality, gender, and relationships.'),
    (12, 'HIS 101 - Western Civilization: From Ancient to Early Modern Times',3, 'This course analyzes the societies of Western civilization from their origin to early modern times. The major social, economic, political, religious and intellectual developments are examined and their impact on the development of modern Western civilization is traced.'),
    (13, 'HIS 102 - Western Civilization: The Emergence of the Modern World',3, 'This course traces the growth of the modern Western world to the present. It surveys the political, economic and social foundations of contemporary civilization.'),
    (14, 'LIN 100 - Language and Culture',3, 'This course will introduce the student to the study of Language and Culture. The course will introduce related topics, such as bilingual/bidialectal families and bilingual education, language and gender, literacy in a changing, technological society, child language acquisition, and different dialects and registers of English. The readings will draw on works in linguistics, literature and related fields. Students will work on critical reading and produce writing based on the readings in connections with their own experiences and backgrounds.'),
    (15, 'MES 152 - Introduction to Contemporary Media',3, 'This course introduces students to varied applications of contemporary media in business, entertainment, and the public sector. Students study the processes of media production, the systems for media distribution, and the roles of media professionals. The course surveys the history of modern communications and the terminology of the media industry. Students examine the complex connections between technology, content, style, and audience response in the creation of media productions.'),
    (16, 'PHI 100 - Philosophy',3, 'The study of philosophy helps students develop analytic skills and gain an appreciation of the general philosophical problems with which human beings have grappled throughout Western civilization. Basic philosophic problems such as free will and determinism, the criteria which justify ethical evaluations, the philosophical considerations which are relevant to belief or disbelief in God, and knowledge and illusion are examined during this course.'),
    (17, 'PHI 120 - Ethics',3, 'This course will examine major historical and contemporary perspectives in moral philosophy. We will consider questions such as, ''Are there universal moral values?'', ''Are ethical conduct and self-interest compatible?'', ''What is the source of our ethical obligations (God? Society? Or Reason?) and how can we justify them?'', and ''How does globalization impact ethical theory?'' The course will look at what attributes and qualities make up a successful ethical theory and will compare competing approaches to ethical decision-making. Throughout the course, the emphasis will be on real...'),
    (18, 'PHY 101 - Physics', 3, 'This course provides an introduction to the principles and applications of physics. Topics covered include mechanics, thermodynamics, waves, electricity, and magnetism. The course emphasizes problem-solving skills and the application of physical principles to real-world situations.'),
    (19, 'PSY 200 - Introduction to Psychology', 3, 'Introduction to Psychology is a survey course that provides an overview of the major topics and theories in psychology. Topics covered include the scientific method in psychology, biological bases of behavior, perception, learning, memory, motivation, emotion, personality, social psychology, and psychological disorders.'),
    (20, 'SOC 100 - Introduction to Sociology', 3, 'Introduction to Sociology is a comprehensive survey of the basic concepts and principles of sociology. Topics covered include social interaction, social structure, culture, deviance, socialization, stratification, race and ethnicity, gender, family, education, religion, and social change.'),
    (21, 'STA 101 - Statistics', 3, 'This course provides an introduction to statistical methods and data analysis. Topics covered include descriptive statistics, probability, hypothesis testing, confidence intervals, correlation, regression, and basic experimental design. Emphasis is placed on understanding statistical concepts and applying them to real-world problems.');
-- Create the U.S. Experience in Its Diversity table
CREATE TABLE `US_Experience_in_Its_Diversity` (
  `id` INT PRIMARY KEY,
  `credit` INT,
  `course_name` VARCHAR(255),
  `description` TEXT
);

-- Insert data into the U.S. Experience in Its Diversity table
INSERT INTO `US_Experience_in_Its_Diversity` (`id`, `course_name`,`credit`, `description`) VALUES
    (22, 'ACR 150 - Literacy in American Society', 3, 'Literacy in American Society asks students to investigate the varieties of literacy behaviors in American society as sociocultural phenomena. Students will be exposed to the research of major scholars in the interdisciplinary field of literacy research (e.g., New Literacy Studies) as a means of considering the role literacy and literacy behavior plays, both historically and in a contemporary context, in a diverse American society. Students will analyze the various definitions of literacy and track the development of multiple literacies in American society, specifically studying the transmission of literacy as a cultural value, particularly in oppressed communities. The course will provide the students with the opportunity to analyze and reflect on their personal relationship with literacy and opportunities for upward mobility in a stratified United States.'),
    (23, 'AFL 100 - Introduction to Ethnic Studies', 3, 'Introduction to Ethnic Studies explores the historical formation of ethnic studies in the United States. The course examines the academic field of Ethnic Studies by raising questions about the ways that race and racism shape our experiences and world across a range of time and places. In an interdisciplinary approach, the course will introduce students to a variety of terms such as ethnicity, race, class, gender, ethnic stratification, etc. The course will also teach students a variety of methodological approaches to doing ethnic studies research and major issues in the field. It places an emphasis on relationships and conflicts between diverse groups, especially how they were treated and defined in relation to each other. Broadly speaking, this course is concerned with how these groups struggle to stake out their place in a highly unequal world.'),
    (24, 'AFL 125 - Comparative Ethnic Studies', 3, 'This course surveys the long history of cross-racial and inter-ethnic interactions among immigrants, migrants, people of color and working people in the United States and the wider world from the era of mercantile capitalism in the sixteenth century to the present. By making inroads into the dynamic worlds that indigenous people, people of African and Latin American descent, European Americans, and Asian Americans made and remade, the course aims to reach across borders of all kinds, including national boundaries, to cultivate global, transnational and comparative perspectives on race and ethnicity. In particular, it places emphasis on relationships and conflicts between these diverse groups, especially how they were treated and defined in relation to each other. Broadly, this course is concerned with how these groups struggle to stake out their place in a highly unequal world.'),
    (25, 'AFL 161 - Health Problems in Urban Communities', 3, 'This course analyzes the relationships between economic and social factors, and the delivery of health care services in urban communities. Attention is given to community needs related to HIV/AIDS, tuberculosis, mortality rates, prevention, and education. Guest lecturers and workshops are presented.'),
    (26, 'AFN 123 - African-American History, 17th Century to 1865', 3, 'This course is a systematic examination of the participation of African American people in the political, economic and cultural history of the United States. The involvement of African Americans in abolitionism and in the development of social and cultural institutions in free black communities is analyzed.'),
    (27, 'AFN 124 - African-American History, 1865 to Present', 3, 'Reconstructions I and II, the social Darwinist years, Civil Rights activism of the 1960s, and the cumulative effects of institutionalized racism are set in an historical framework for comparative study. The course examines the impact of urbanization, institutional racism, economic, and political policies on the life experiences of African-Americans. The dynamics of cultural, social, and political interactions within the social structure of the nation since 1865 are analyzed.'),
    (28, 'AFN 129 - The Black Man in Contemporary Society', 3, 'The effects of economic and social factors on socialization, status, and levels of achievement among Black men are analyzed. The impact of institutional racism and underachievement on urbanized populations is explored in terms of access, social status, and economic differentials.'),
    (29, 'ASN 114 - Asian American History', 3, 'The Asian American presence from the mid-nineteenth century to the present is studied. Three periods, 1848 to 1943, 1943 to 1965, and 1965 to the present are examined. Topics are designed to focus on the impact of historical processes on the cultural, economic, and political experiences of diverse Asian American groups in urban and rural communities. The multi-ethnic aspects of Asian American communities are explored.'),
    (30, 'ASN 211 - Asian Americans in NYC', 3, 'According to the 2010 census, 1 in 8 New Yorkers are of Asian descent. Yet the histories and identities of Asian American communities in New York City, and on the East Coast more generally, have not been as visible in academic scholarship as Asian Americans on the West Coast. This class will examine the diverse Asian American communities that have populated the city from the late 19th century onwards through topics such as racial segregation, ethnic economies and labor, global and transnational flows, gentrification, community institutions and inter-racial community relations. One of the main goals for this class is for students to experience Asian American spaces in NYC with a scholar’s eye. To this end, the class will study research methods, undertake field trips to Asian American and transnational Asian institutions and organizations, and produce a final paper based on first-hand/primary research.'),
    (31, 'ECO 201 - Macroeconomics', 3, 'This course is intended primarily for those students who intend to pursue professional careers in fields such as economics, finance, management, and administration. It is also open to highly motivated students in other areas. Topics include: national income and national product; saving, consumption, investment, the multiplier theory, fiscal policy, inflation, employment and business cycles. The student will also be acquainted with money, banking, and central bank monetary policies, as well as some of the more significant theories of international trade and economic development.'),
    (32, 'HED 195 - Food, Culture and Society', 3, 'Students will examine American dining rituals and patterns from colonial times through the 21st Century. Students will examine how historical events of colonization, trade, war, industrialization and weather impacted food consumption and diet in America. Using a socioecological model, students will also examine how American meal patterns are influenced by religion, race, culture, economics and politics.'),
    (33, 'HIS 120 - Early American History: Colonial Period to Civil War', 3, 'In this course, the history of the United States from the Colonial period to the Civil War is studied and the major political, economic, and social problems of the new nation are analyzed.'),
    (34, 'HIS 125 - Modern American History: Civil War to Present', 3, 'This continued study of American history emphasizes the emergence of an industrial economy, an urban society, world responsibility, and the expanded federal government.'),
    (35, 'LAT 125 - Puerto Rican Culture and Folklore', 3, 'This course studies the emergence of a national culture, folklore and identity. Topics include the Taino, Spanish and African contributions to the creation of a criollo personality and character and the Puerto Rican family, race relations, the jibaro, religion, and the arts. It reviews customs, traditions, celebrations, dances, legends, songs, proverbs, and hero/underdog stories as well as the impact of the United States culture.'),
    (36, 'LAT 140 - Introduction to Mexican-American Studies', 3, 'This course studies the varied experiences of Mexicans in the United States from an interdisciplinary perspective. Through readings, lectures, media and discussions, students will learn about the historical, social and cultural contributions of Mexican Americans. The course will survey the history and evolution of Mexicans in the United States at the same time that it explores issues culture and identity. While the course emphasizes developments in the 20th and 21st centuries, students will also engage with developments prior to the 20th century. Students will study major political and social events that contributed to the incorporation of Mexicans into US institutions as well as become familiar with current events and perspectives regarding the experiences in today’s society.'),
    (37, 'LAT 150 - The Latino Experience in the U.S.', 3, 'This course studies the varied experiences of Latinos in the United States of America. Through readings, lectures, discussions, and fieldwork, students will become familiar with the group and its diverse components from North, Central and South America as well as the Caribbean, while covering representative nationalities such as Mexicans, Salvadorians, Cubans, Colombians, Ecuadorians, Puerto Ricans and Dominicans. The course will survey the history and evolution of Latinos at the same time that it explores issues of culture and identity. Other topics include family, race relations, religion, education, economic incorporation, and political participation. Key issues of contemporary interest will also be explored, such as Latinos and immigration, and the impact they have on local, state and nationwide elective office.'),
    (38, 'LIN 150 - Language, Race, and Ethnicity in the US and its Territories', 3, 'This course explores historical, cultural, and theoretical perspectives on the relationship between language, race, and ethnicity in the United States and its territories. It examines how language is understood to reflect, reproduce, and/or challenge and defy racial and ethnic boundaries, and how ideas about race and ethnicity influence the ways in which people use and construe language. It covers topics such as racialization and racism, ethnicization, notions of authenticity, repertoire, codeswitching and style shifting, linguistic mocking and linguistic racism, language ideology, and identity formation. This course will examine language varieties such as Black American English and its cross-racial uses by other groups, Chicano English and Spanglish, Hawaiian English, and American Indian English.'),
    (39, 'POL 100 - American Government', 3, 'The history, development, and intellectual origin of American government are studied and analyzed. Special consideration is given to the structure and operation of the executive, legislative, and judiciary branches, and the role of government and politics in a modern industrial society.'),
    (40, 'SPN 485 - New York Literature in Spanish', 3, 'This course consists of a survey of all literary production in Spanish created in New York from the 19th century to the present, mainly focusing on those authors who have lived and written here, whose work was influenced by the circumstance of coming and staying in this city and who are weaving the unique history of literature written in Spanish in New York. Readings and classwork will be conducted in Spanish. Prerequisite: SPN 211 or departmental approval or any 400-level course except SPN 476.');
    -- Create the World Cultures and Global Issues table

CREATE TABLE `World_Cultures_and_Global_Issues` (
  `id` INT PRIMARY KEY,
  `credit` INT,
  `course_name` VARCHAR(255),
  `description` TEXT
);

-- Insert data into the World Cultures and Global Issues table
INSERT INTO `World_Cultures_and_Global_Issues` (`id`, `course_name`,`credit`, `description`) VALUES
    (41, 'ACR 195 - Literacy, Development, and Social Justice', 3, 'In this course, students will examine how, in both “developed” and “developing” contexts, local, national, and global policies and institutions affect an individual’s socialization into and acquisition of literacy (e.g., in educational and social contexts). Specifically, students will examine how socialization into and acquisition of literacy relate to the civic participation and socioeconomic opportunities of members of marginalized and minority communities (e.g., communities organized around gender, class, colonial status, race/ethnicity/tribal affiliation, sexuality, and/or religious sect). Students will analyze, through intersectional and postcolonial lenses, how cultural conventions (e.g., norms, prejudices, hierarchies, and traditions) influence and are influenced by local, national, and global policies related to literacy practices and education (particularly as they relate to gender). Further, students will examine how, in an increasingly globalized and neocolonial world, conceptions of and access to literacies can affect a) the maintenance of cultural values and practices and b) an individual’s rights, agency, and mobility (particularly as these phenomena relate to gender). Emphasis will be on how literacy acquisition, civic participation, social justice, and socioeconomic opportunities relate to how gendered individuals are valued, perceived, and defined in various cultural contexts.'),
    (42, 'AFN 121 - History of African Civilization', 3, 'African civilizations from the pre-historic cultures in East Africa to the decline of the West African kingdom of Songhai in 1596 are examined.'),
    (43, 'AFN 122 - Africa 1500 to Present', 3, 'Africa from the beginnings of the Atlantic slave trade to the end of Colonialism in the late twentieth century is examined. The effect of Colonialism on economic and cultural patterns in the African diaspora is explored.'),
    (44, 'AFN 128 - Black Women in the Americas and the Caribbean', 3, 'The changing status of women in African traditional societies is compared with changes in the status of Black women in the United States, the Caribbean, and Brazil.'),
    (45, 'ANT 100 - Introduction to Anthropology', 3, 'The evolution and behavior of human beings as cultural animals are the focus of this course. Students are introduced to the basic concepts and methods of the major divisions of anthropology: physical, social and cultural; archeology and linguistics. Emphasis is placed on preliterate societies to facilitate the study of the interrelation of various aspects of culture.'),
    (46, 'ANT 200 - Peoples & Cultures of Latin America and the Caribbean', 3, 'This course examines the diverse peoples and cultures that have populated Latin American and the Caribbean region since pre-Columbian times. It discusses the legacy of European colonization and the subsequent struggles for independence, formation of national identities and the quest for modernization today. The course will place particular emphasis on the production of social movements that respond to social inequality, and conflicting ideologies around ethnicity, race and gender among other factors. The readings illustrate case studies that examine a wide range of topics - ecological adaptation, food production, kinship and local politics, medical and religious beliefs and artistic expressions - from small-scale rural society to large complex urban centers throughout the continent. It will also explore how globalization, intense migration, and transnationalism have generated new notions of identity in the US today.'),
    (47, 'ASN 111 - Chinese Culture and Heritage', 3, 'In this course students will inquire into the nature of classical traditions of Chinese culture. A range of Chinese texts in translation and associated materials will be explored to develop knowledge of the literary and philosophical foundations of Chinese culture. Lectures and readings are in English.'),
    (48, 'COM 255 - Intercultural Communication', 3, 'This course is designed to provide an understanding of intercultural principles and perspectives when communicating with people from diverse cultures. Consideration will be given to both verbal and nonverbal communication processes in the "American" culture, co-cultures, contact cultures, and popular culture. Through readings, lectures, response papers, and interviews, as well as through in-class discussion and exercises, this course will explore how culture shapes communication, how situations are framed through cultural lenses, and how histories, perceptions, values, contexts, aspects of stereotypes, and ethnocentrism all contribute to the complexity of intercultural communication. Prerequisite: SPE 100 or SPE 102'),
    (49, 'GEO 100 - Introduction to Human Geography', 3, 'This course introduces students to the key concepts and principles of human geography. The course is designed to show how world geographic conditions such as climate, landform, natural resources, soil, space and ecology have influenced human culture and civilization over time.'),
    (50, 'LAT 130 - History of Latin America', 3, 'Survey covering from the pre-Columbian cultures, the age of discovery and exploration, colonial structures, independence movements, to contemporary Latin America, with special emphasis on the countries of the mainland (i.e., North, Central, and South America). Students will learn about the traditions and institutions of Latin American Civilization including the Iberian conquest and colonization, the role of the Catholic Church, economic and social structures, as well as problems related to government, nation-building, race and class relations, wars and Latin America''s position in the world.'),
    (51, 'LAT 131 - History of the Dominican Republic', 3, 'This course studies the history of the Dominican Republic from the pre-Columbian and Colonial periods to the present. It deals with the geographical, political, social and economic factors that form the Dominican nation. Emphasis is given to relations with Haiti and North America. The course also analyzes the position of the Dominican Republic in the community of Latin American nations as well as its place in today''s world.'),
    (52, 'LAT 200 - Peoples & Cultures of Latin America and the Caribbean', 3, 'This course examines the diverse peoples and cultures that have populated Latin American and the Caribbean region since pre-Columbian times. It discusses the legacy of European colonization and the subsequent struggles for independence, formation of national identities and the quest for modernization today. The course will place particular emphasis on the production of social movements that respond to social inequality, and conflicting ideologies around ethnicity, race and gender among other factors. The readings illustrate case studies that examine a wide range of topics - ecological adaptation, food production, kinship and local politics, medical and religious beliefs and artistic expressions - from small-scale rural society to large complex urban centers throughout the continent. It will also explore how globalization, intense migration, and transnationalism have generated new notions of identity in the US today.'),
    (53, 'LIN 140 - World Global Englishes', 3, 'The survey course will introduce students to varieties of English around the world. (e.g., African and Caribbean varieties of English, English based Pidgins and Creoles). Students will be introduced to theories of language variation, examine forces that contribute to variation (e.g., colonization, language contact, and globalization), and describe the impact of English on other languages. Attitudes toward different varieties of English will be explored, with students analyzing how we perceive varieties of English and how these perceptions affect linguistic identities and ideologies. Implications of global variations of English for educational practices and language learning will also be discussed.'),
    (54, 'MES 140 - Introduction to the Moving Image', 3, 'This course examines the diverse peoples and cultures that have populated Latin American and the Caribbean region since pre-Columbian times. It discusses the legacy of European colonization and the subsequent struggles for independence, formation of national identities and the quest for modernization today. The course will place particular emphasis on the production of social movements that respond to social inequality, and conflicting ideologies around ethnicity, race and gender among other factors. The readings illustrate case studies that examine a wide range of topics - ecological adaptation, food production, kinship and local politics, medical and religious beliefs and artistic expressions - from small-scale rural society to large complex urban centers throughout the continent. It will also explore how globalization, intense migration, and transnationalism have generated new notions of identity in the US today.'),
    (55, 'MES 160 - World History of Animation', 3, 'World History of Animation introduces students to seminal works of animation across time and cultures. The course discusses the evolution of the art form through the lens of technical innovations, socio-political contexts, and aesthetic movements. Students will study works ranging from large productions to independent and experimental shorts, and the influence of different international productions on one another, including Asian and European works and creators.'),
    (56, 'POL 111 - Political Economy of Technoscience', 3, 'Science, technology and society is constructively and deconstructively theorized within fields of knowledge known as textual and political economies. In considering competing intellectual traditions in creating a theory of science, technology, and society, themes such as the relationship between science, technology and the state; social epistemology; laboratory science studies; feminist perspectives on science and technology; ecological foundations for science and technology; and the globalization of science and technology will be discussed. This course will provide acquaintance with the everyday context of working scientists and technologists.'),
    (57, 'TRS 231 - Introduction to Translation and Interpretation Theory', 3, 'In this introductory course students learn about the processes and strategies of translation and interpretation as well as available resources. This course includes translation and interpretation ethics, types of translation and interpretation and the history of the profession. Students are introduced to the use of interpretation and translation in law, the health professions, and financial businesses. It also introduces terminology and resources that can be used in computer aided interpretation and translation. Students explore how computer-assisted interpretation and translation has affected the industry as they learn to use interpretation and translation tools and create lists of commonly used terminology. There is emphasis on interpretation and translation into the native language with some practice in the opposite direction. Prerequisite: ENG 101 and Spanish at the intermediate-low level (SPN 200/SPN 108 or above). Language level will be determined with language proficiency exams administered by the Modern Languages Department.'),
    (58, 'TRS 233 - Spanish Translation & Interpretation for Healthcare', 3, 'This is a theory based fully online course dealing with English-Spanish translation and interpretation for health care. As such, it addresses the communication needs in settings such as hospitals, clinics, physician''s offices, dental offices, outpatient facilities, pharmacies, etc. Among the topics or scenarios to be covered are: Spanish-speaking clients and their health; specialized terminology (e.g., anatomic, physiological, neurological, cardiovascular, oncological, obstetrical, orthopedic, medical instruments and devices); communication with administrative personnel (e.g., admission, payment, insurance); patient''s medical history (present illness and past history); personal, social and family history; the physical examination; emergency room; labor and delivery; surgery; medication and prescriptions; diet; treatments; drug overdose; patient instructions; dental visit and treatment; authorizations, consents and signature forms; and visits with different types of specialists (e.g., neurologist, orthopedist, cardiologist, psychiatrist). Prerequisite: TRS 232 or departmental permission.');
-- Create the Program Electives table
CREATE TABLE `Program_Electives` (
  `id` INT PRIMARY KEY,
  `credit` INT,
  `course_name` VARCHAR(255),
  `description` TEXT
);

-- Insert data into the Program Electives table
INSERT INTO `Program_Electives` (`id`, `course_name`, `credit`,`description`) VALUES
(59, 'CIS 345 - Telecommunication Networks I', 3, 'This course is an introductory course in telecommunications networks. It covers the fundamentals of networking concepts, such as networking media, topology, switching, and management. It will also include an introduction to Open System Interface (OSI) layered organization and the functionality of each layer. Prerequisite: CSC 110 or CIS 165 or CSC 111 or Departmental Permission'),
(60, 'CIS 359 - Information Assurance', 3, 'This course introduces the fundamentals of information security in the context of computer vulnerabilities/threats and how to safeguard computers and networks. The students will be exposed to the concepts of security planning, security technologies, security organization and the legal and ethical issues associated with implementing computer and network security. Prerequisite: CSC 210, CSC 211 or CIS 255 or Departmental Approval'),
(61, 'CIS 362 - Cloud Computing', 3, 'This course introduces students to the principles, foundations, and applications of Cloud computing. Different types of features, standards, services, and security issues in Cloud computing will be discussed. The students will study the paradigm of computing in which dynamically scalable and often virtualized resources are offered as services over the Internet. Through hands-on assignments and projects, students will learn how to configure and program Infrastructure as a Service (IaaS), how to develop Cloud-based software applications on top of various Cloud platforms, and how to integrate application-level services built on heterogeneous Cloud platforms. Prerequisites: CSC 110 or CSC 111 or Departmental approval'),
(62, 'CIS 364 - Mobile Device Programming', 3, 'This course introduces the unique requirements and methodologies necessary to develop applications for mobile devices. The course will focus on installing, developing, and testing mobile applications. Students will learn the basic framework of a mobile application, mobile user interface design, methods for storing and retrieving information, and mobile security. Prerequisites: CSC 210 or Departmental approval'),
(63, 'CIS 385 - Web Programming I', 3, 'This course introduces students to client-side web programming. Emphasis is placed on structure, formatting and scripting of web pages as well as manipulation of media elements to solve elementary level application problems. A variety of client-based technologies are introduced to facilitate the understanding of design and programming concepts in a web environment. A final project consisting of the creation of an online application will be developed. Prerequisite: CSC 110 or CSC 111 or department approval'),
(64, 'CIS 395 - Database Systems I', 3, 'This course introduces the design, implementation, testing, and manipulation of database management systems. The design techniques include conceptual data modeling, entity relational modeling and normalization techniques. The databases are then implemented using structured query languages. Testing strategies verify data integrity, security, and privacy. Manipulation activities include insert, update, and delete operations. Prerequisite: CSC 110 or CSC 111 or department approval'),
(65, 'CSC 103 - Introduction to Data Analytics', 3, 'This course is an introduction to the analysis of data. Topics include data preparation exploratory data analysis and data visualization. Some of the most commonly used classification and clustering techniques will also be covered. Students will apply these topics to real-world problems including science, business and engineering fields.'),
(66, 'GIS 201 - Introduction to Geographic Methods', 4, 'This course introduces the means by which geographers analyze the world to better understand geography and geographical processes. It teaches the students various methods for interpreting and analyzing spatial data including cartography, Geographic Information Systems (GIS), remote sensing, spatial statistics and survey research.');
(67, 'CIS 317 - Introduction to Cryptography', 4, 'This course provides students with the cryptographic practices, protocols and mathematics necessary to accomplish information and communication security. Topics include history of cryptography; symmetric encryption methods; mathematics background for asymmetric methods; asymmetric methods used in cryptography and cryptographic primitives and their application. Not offered in Fall 2023');

 