# Generated by Django 4.2.3 on 2023-07-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Club Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Club Email')),
                ('meeting_type', models.CharField(default='On Campus', max_length=100, verbose_name='Hybrid ( On Campus & Virtual )')),
                ('hybrid_link', models.URLField(blank=True, verbose_name='Hybrid Link ( If Applicable )')),
                ('advisor_name', models.CharField(max_length=100, verbose_name='Advisor Name')),
                ('advisor_email', models.EmailField(max_length=254, verbose_name='Advisor Email')),
                ('club_room', models.CharField(max_length=100, verbose_name='Club Room')),
                ('active', models.CharField(default='Active', max_length=100)),
            ],
        ),
    ]
