# Generated by Django 4.2.3 on 2023-07-12 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_category_club_members_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='members',
            new_name='club_members',
        ),
    ]
