# Generated by Django 4.2.3 on 2023-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_rename_members_club_club_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Mentee Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Mentee First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Mentee Last Name')),
                ('emplid', models.IntegerField(default=0, verbose_name='EmplID')),
                ('major', models.CharField(max_length=100, verbose_name='Mentee Major')),
                ('language', models.CharField(max_length=100, verbose_name='Prefferred Language')),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic Clubs'), ('Creative', 'Creative Clubs'), ('Diversity/Multicutural', 'Diversity Clubs'), ('Professional', 'Professional Clubs'), ('Religious', 'Religious Clubs'), ('Social Service', 'Social Service Clubs'), ('Sports', 'Sports Clubs')], max_length=255),
        ),
    ]
