# Generated by Django 4.2.3 on 2023-07-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_mentee_alter_club_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentee',
        ),
    ]
