# Generated by Django 4.2.3 on 2023-07-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_rename_members_club_club_members'),
        ('myapp', '0002_rename_mentee_field_customuser_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clubs',
            field=models.ManyToManyField(related_name='members', to='clubs.club'),
        ),
    ]
