# Generated by Django 4.2.3 on 2023-07-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mentee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('morning', 'In the morning (9:45 AM - 11:45 AM)'), ('afternoon', 'In the afternoon (3:00 PM - 5:00 PM)'), ('both', 'Both'), ('conflicts', 'Neither, I have scheduling conflicts, please follow up')], default='both', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emplid', models.CharField(max_length=10)),
                ('rsvp_session', models.CharField(choices=[('07/06', '07/06 (Thursday) at 12:00 PM - 1:30 PM'), ('06/10', '06/10 (Monday) at 3:00 PM - 4:30 PM'), ('follow_up', 'I cannot attend either session, please follow up')], default='follow_up', max_length=20)),
                ('mhfa_certification', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('training_availability', models.ManyToManyField(blank=True, to='myapp.trainingavailability')),
            ],
        ),
    ]
