# Generated by Django 4.2.3 on 2023-07-18 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_trainingavailability_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='id',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='availability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='emplid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mhfa_certification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='rsvp_session',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='training_availability',
        ),
        migrations.DeleteModel(
            name='TrainingAvailability',
        ),
        migrations.AddField(
            model_name='mentor',
            name='training_availability',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
