# Generated by Django 4.2.3 on 2023-07-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_mentee_user_alter_mentor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='preferred_language',
            field=models.CharField(default='English', max_length=100, verbose_name='Preferred Language'),
        ),
    ]
